name: Build EdiZon

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'   
    # - name: Install devkitPro libraries
    #   run: sudo dkp-pacman -S switch-{dev,curl,freetype} --noconfirm --disable-download-timeout
    - name: Install libnx from submodule
      run: sudo make install -C ./libs/libnx/nx