name: Build EdiZon
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Download devkitpro
      run: wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
    - name: Install devkitPro pacman
      run: sudo dpkg -i devkitpro-pacman.deb
    - name: Install devkitPro libraries
      run: sudo dkp-pacman -S switch-{dev,curl,freetype} --noconfirm
    - name: Install libnx from submodule
      run: |
        ls /etc/profile.d
        cat /etc/profile.d/devkit-env.sh
        sh /etc/profile.d/devkit-env.sh
        sudo make install -C ./libs/libnx/nx
